tasks:
  - name: Install and run smee
    init: npm install -g smee-client
    command: smee -u https://smee.io/elJV8uk66HIXM
  - name: Create an .env file
    command: |
      cat > .env << EOF
      APP_ID=953917
      WEBHOOK_SECRET=secret
      LOG_LEVEL=trace
      WEBHOOK_PROXY_URL=https://smee.io/elJV8uk66HIXM
      EOF
  - name: Run the probot app
    init: npm install
    command: npm start
